'use client';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {X,ChevronLeft,ChevronRight,ZoomIn,ZoomOut} from 'lucide-react';
export default function PhotoViewer({images,index,name,onIndex,onClose}:{images:string[];index:number;name:string;onIndex:(index:number)=>void;onClose:()=>void}){
 const root=useRef<HTMLDivElement>(null),stage=useRef<HTMLDivElement>(null),touch=useRef<{x:number;y:number}|null>(null);
 const [zoom,setZoom]=useState(false);
 const move=(delta:number)=>{setZoom(false);onIndex((index+delta+images.length)%images.length)};
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;root.current?.querySelector<HTMLButtonElement>('[aria-label="Закрыть просмотр фото"]')?.focus();return()=>previous?.focus()},[]);
 useEffect(()=>{if(stage.current){stage.current.scrollTop=zoom?(stage.current.scrollHeight-stage.current.clientHeight)/2:0;stage.current.scrollLeft=zoom?(stage.current.scrollWidth-stage.current.clientWidth)/2:0}},[index,zoom]);
 useEffect(()=>{function key(e:KeyboardEvent){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();onClose()}else if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();e.stopImmediatePropagation();move(e.key==='ArrowRight'?1:-1)}else if(e.key==='Tab'){e.stopImmediatePropagation();const buttons=[...(root.current?.querySelectorAll<HTMLButtonElement>('button:not([disabled])')||[])];const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}}document.addEventListener('keydown',key,true);return()=>document.removeEventListener('keydown',key,true)},[index,images.length,onClose]);
 return createPortal(<div ref={root} onClick={e=>e.stopPropagation()} className="photo-viewer" role="dialog" aria-modal="true" aria-label={`Фотографии: ${name}`}><div className="viewer-bar"><div><strong>{name}</strong><span aria-live="polite">Фото {index+1} из {images.length}</span></div><button aria-label={zoom?'Уменьшить фото':'Увеличить фото'} aria-pressed={zoom} onClick={()=>setZoom(v=>!v)}>{zoom?<ZoomOut/>:<ZoomIn/>}</button><button aria-label="Закрыть просмотр фото" onClick={onClose}><X/></button></div>
 <div ref={stage} className={'viewer-stage'+(zoom?' is-zoomed':'')} onTouchStart={e=>{touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(!touch.current||zoom)return;const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))move(dx<0?1:-1);touch.current=null}}><img src={images[index]} alt={`${name} — фото ${index+1}`} onDoubleClick={()=>setZoom(v=>!v)}/></div>
 {images.length>1&&<><button className="viewer-prev" aria-label="Предыдущее фото в полном размере" onClick={()=>move(-1)}><ChevronLeft/></button><button className="viewer-next" aria-label="Следующее фото в полном размере" onClick={()=>move(1)}><ChevronRight/></button></>}
 <div className="viewer-bottom"><p>{zoom?'Перемещайтесь по фотографии, чтобы рассмотреть детали':'Увеличьте фото, чтобы рассмотреть фактуру и детали'}</p><div className="viewer-thumbs">{images.map((src,i)=><button key={src} aria-label={`Открыть фото ${i+1} в полном размере`} aria-pressed={index===i} onClick={e=>{setZoom(false);onIndex(i);e.currentTarget.scrollIntoView({block:'nearest',inline:'nearest'})}}><img src={src} alt=""/></button>)}</div></div></div>,document.body)
}
