'use client';
import {useEffect,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,ShoppingBag,X} from 'lucide-react';
type Product={id:string;name:string;category:string;image:string;description:string;stock:number;price:number;discount:number;source:string};
export type CustomizationOptions={name:string;values:string[]}[];
type Details={images:string[];specifications:{name:string;value:string}[];description?:string[];photoColor?:string|null;customizationOptions?:CustomizationOptions};
const cache=new Map<string,Details>();
export default function ProductDialog({product,onClose,onCustom,onAdd}:{product:Product;onClose:()=>void;onCustom:(options:CustomizationOptions)=>void;onAdd:()=>Promise<void>}){
 const [details,setDetails]=useState<Details|null>(cache.get(product.id)||null),[loading,setLoading]=useState(!cache.has(product.id)),[error,setError]=useState(false),[index,setIndex]=useState(0),[adding,setAdding]=useState(false),[retry,setRetry]=useState(0);
 const dialog=useRef<HTMLDivElement>(null),start=useRef<{x:number;y:number}|null>(null);
 const images=details?.images.length?details.images:[product.image];
 useEffect(()=>{if(cache.has(product.id)){setDetails(cache.get(product.id)!);setLoading(false);return}const controller=new AbortController();setLoading(true);setError(false);fetch(`/product-details/${encodeURIComponent(product.id)}.json`,{signal:controller.signal}).then(async r=>{if(r.status===404)return {images:[],specifications:[]};if(!r.ok)throw Error('details');return await r.json() as Details}).then(data=>{if(controller.signal.aborted)return;cache.set(product.id,data);setDetails(data);setIndex(0)}).catch(()=>{if(!controller.signal.aborted)setError(true)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[product.id,retry]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.querySelector<HTMLButtonElement>('.close')?.focus();function trap(e:KeyboardEvent){if(e.key!=='Tab')return;const nodes=[...(dialog.current?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],[tabindex="0"]')||[])].filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}document.addEventListener('keydown',trap);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',trap);previous?.focus()}},[]);
 function move(delta:number){setIndex(i=>(i+delta+images.length)%images.length)}
 return <div className="overlay" onClick={onClose}><div ref={dialog} className="modal product-modal product-detail-dialog" role="dialog" aria-modal="true" aria-labelledby="product-dialog-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Закрыть карточку товара" onClick={onClose}><X/></button>
 <div className="product-visual-column"><div className="product-gallery" role="region" aria-roledescription="карусель" aria-label="Фотографии товара" tabIndex={0} onKeyDown={e=>{if(e.target instanceof HTMLButtonElement)return;if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}}}>
 <div className="gallery-stage" onTouchStart={e=>{start.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchEnd={e=>{if(!start.current)return;const dx=e.changedTouches[0].clientX-start.current.x,dy=e.changedTouches[0].clientY-start.current.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))move(dx<0?1:-1);start.current=null}}>
 <img key={images[index]} src={images[index]} alt={`${product.name} — фото ${index+1}`} decoding="async" onError={e=>{if(e.currentTarget.getAttribute('src')!==product.image)e.currentTarget.src=product.image}}/>
 {images.length>1&&<><button className="gallery-arrow previous" aria-label="Предыдущее фото" onClick={()=>move(-1)}><ChevronLeft/></button><button className="gallery-arrow next" aria-label="Следующее фото" onClick={()=>move(1)}><ChevronRight/></button></>}
 <span className="gallery-counter" aria-live="polite" aria-atomic="true">{index+1} / {images.length}</span></div>
 {images.length>1&&<div className="gallery-thumbnails" aria-label="Выбор фотографии">{images.map((src,i)=><button key={src} className={index===i?'selected':''} aria-label={`Показать фото ${i+1}`} aria-pressed={index===i} onClick={e=>{setIndex(i);e.currentTarget.scrollIntoView({block:'nearest',inline:'nearest',behavior:'smooth'})}}><img src={src} alt="" loading="lazy"/></button>)}</div>}
 {loading&&<p className="details-note" role="status">Загружаем фотографии и характеристики…</p>}
 </div>
 <section className="product-story" aria-labelledby="product-story-title"><span className="eyebrow">ХАРАКТЕР В ДЕТАЛЯХ</span><h3 id="product-story-title">О модели</h3>{(details?.description||[product.description]).filter(Boolean).map((paragraph,i)=><p key={i}>{paragraph}</p>)}<a className="source-link" href={product.source} target="_blank" rel="noreferrer">Товар в исходном каталоге ↗</a></section></div>
 <div className="product-details-copy"><span className="eyebrow">{product.category}</span><h2 id="product-dialog-title">{product.name}</h2><p className="large-price">{new Intl.NumberFormat('ru-RU').format(Math.round(product.price*(1-product.discount/100)))} ₽</p><p className="muted">{product.stock?'В наличии':'Изготовление на заказ'}. Отделку и комплектацию согласуем перед оформлением.</p><div className="product-detail-actions"><button className="primary" disabled={adding} onClick={async()=>{setAdding(true);try{await onAdd()}finally{setAdding(false)}}}>{adding?'Добавляем…':'В корзину'}<ShoppingBag size={18}/></button><button className="outline" onClick={()=>onCustom(details?.customizationOptions||[])}>Изменить размеры или цвет</button></div>
 <section className="product-specifications" aria-labelledby="specifications-title"><h3 id="specifications-title">Характеристики</h3>{error?<div className="details-error" role="alert"><p>Не удалось загрузить характеристики и дополнительные фото. Проверьте соединение и попробуйте ещё раз.</p><button className="outline" onClick={()=>setRetry(n=>n+1)}>Повторить загрузку</button></div>:loading?<p className="muted">Загружаем данные товара…</p>:details?<dl><div><dt>Цвет</dt><dd>{details.photoColor||'Как на фото'}</dd></div>{details.specifications.map(s=><div key={s.name}><dt>{s.name}</dt><dd>{s.value}</dd></div>)}</dl>:<p className="muted">В исходном каталоге характеристики не указаны. Уточните детали у менеджера.</p>}</section>
 <p className="details-note">Цвет может немного отличаться на разных экранах. Оттенок и образец отделки согласуем перед изготовлением.</p></div></div></div>;
}
